stages:
  - source
  - build
  - docs

variables:
  NIX_PATH: "nixpkgs=./."

make:ormolu:
  stage: source
  tags:
    - kvm
    - nix
  script: nix-shell -p gnumake --run "make ormolu"

make:hlint:
  stage: source
  tags:
    - kvm
    - nix
  script: nix-shell -p gnumake --run "make hlint"

make:shellcheck:
  stage: source
  tags:
    - kvm
    - nix
  script: nix-shell -p gnumake --run "make shellcheck"

nix:package:
  stage: build
  tags:
    - kvm
    - nix
  script: nix-build -A hbandit --no-build-output


make:readme:
  stage: build
  tags:
    - kvm
    - nix
  script: nix-shell -p gnumake --run "make README.md"

make:doc:
  stage: build
  tags:
    - kvm
    - nix
  script: nix-shell -p gnumake --run "make doc"

readthedocs:
  stage: docs
  when: on_success
  only:
    - master
    - staging
  tags:
    - kvm
    - nix
  script:
    - echo "token=$RTD_TOKEN"
    - nix run nixpkgs.curl -c curl --fail -X POST -d "token=$RTD_TOKEN" readthedocs.org/api/v2/webhook/hbandit/109499/
