stages:
  - source
  - lib
  - docs

variables:
  NIX_PATH: "nixpkgs=./."

ormolu:
  stage: source
  tags:
    - kvm
    - nix
  script:
    - nix-shell -p gnumake --run "make ormolu"

hlint:
  stage: source
  tags:
    - kvm
    - nix
  script:
    - nix-shell -p gnumake --run "make hlint"

shellcheck:
  stage: source
  tags:
    - kvm
    - nix
  script:
    - nix-shell -p gnumake --run "make shellcheck"

dhall-format:
  stage: source
  tags:
    - kvm
    - nix
  script:
    - nix-shell -p gnumake --run "make dhall-format"

nix-build:
  stage: lib
  tags:
    - kvm
    - nix
  script: nix-build -A hbandit --no-build-output

readthedocs:
  stage: docs
  when: on_success
  only:
    - master
    - staging
  tags:
    - kvm
    - nix
  script:
    - echo "token=$RTD_TOKEN"
    - nix run nixpkgs.curl -c curl --fail -X POST -d "token=$RTD_TOKEN" readthedocs.org/api/v2/webhook/hbandit/109499/
