stages:
  - lib
  - afterlib
  - codegen
  - linked

nrm.so:
  stage: lib
  script: nix-build -A haskellPackages.nrmlib
  tags:
  - integration

doc:
  stage: afterlib
  script: nix-build -A haskellPackages.nrmlib.doc
  artifacts:
    paths:
      - result-doc/*
    expire_in: 1 week
    when: always
  tags:
  - integration

binaries:
  stage: afterlib
  script: nix-build -A haskellPackages.nrmbin
  tags:
  - integration

resources:
  stage: codegen
  script: nix-build -A resources
  tags:
  - integration

libnrm:
  stage: linked
  script: nix-build -A libnrm
  tags:
  - integration

pynrm:
  stage: linked
  script: nix-build -A pynrm
  tags:
  - integration
