nrm.so:
  script: nix-build -A haskellPackages.nrmlib
  tags:
  - integration

#doc:
  #script: ./shake doc
  #artifacts:
    #paths:
    #- ./html/
    #expire_in: 1 month
  #tags:
  #- integration
  #- notknl
