#!/usr/bin/env python
###############################################################################
# Copyright 2019 UChicago Argonne, LLC.
# (c.f. AUTHORS, LICENSE)
#
# This file is part of the NRM project.
# For more info, see https://xgitlab.cels.anl.gov/argo/nrm
#
# SPDX-License-Identifier: BSD-3-Clause
###############################################################################

"""This script generates requirements.txt from the packaged Nix environment."""

import six
import zmq
import yaml
import tornado
import numpy
import argparse
import jsonschema
# import warlock
# import scipy

import os
exists = os.path.isfile('Pipfile')
if exists:
    exit(1)

print("#DO NOT MODIFY: this file is auto-generated by requirements.py")
print("six==%s" % six.__version__)
print("zmq==%s" % zmq.__version__)
print("yaml==%s" % yaml.__version__)
print("tornado==%s" % tornado.version)
print("numpy==%s" % numpy.__version__)
print("argparse==%s" % argparse.__version__)
print("jsonschema==%s" % jsonschema.__version__)
print("warlock")
print("scipy")
