--This file is auto-generated by nrm. Do not modify.
{ verbose :
    < Normal | Verbose >
, logfile :
    Text
, hwloc :
    Text
, perf :
    Text
, argo_perf_wrapper :
    Text
, argo_nodeos_config :
    Text
, pmpi_lib :
    Text
, singularity :
    Text
, container_runtime :
    < Singularity | Nodeos | Dummy >
, downstreamCfg :
    { downstreamBindAddress : Text }
, upstreamCfg :
    { upstreamBindAddress : Text, pubPort : Integer, rpcPort : Integer }
}
