make:hsnrm.nix:
  stage: source
  tags:
    - kvm
    - nix
  script: nix-shell -p gnumake --run "make hsnrm.nix"

make:hsnrm.cabal:
  stage: source
  tags:
    - kvm
    - nix
  script: nix-shell -p gnumake --run "make hsnrm.cabal"

make:ormolu:
  stage: source
  tags:
    - kvm
    - nix
  script: nix-shell -p gnumake --run "make ormolu"

make:hlint:
  stage: source
  tags:
    - kvm
    - nix
  script: nix-shell -p gnumake --run "make hlint"

make:shellcheck:
  stage: source
  tags:
    - kvm
    - nix
  script: nix-shell -p gnumake --run "make shellcheck"

make:dhall-format:
  stage: source
  tags:
    - kvm
    - nix
  script: nix-shell -p gnumake --run "make dhall-format"

make:resources:
  stage: build
  tags:
    - kvm
    - nix
  script: nix-shell -p gnumake --run "make resources"

nix:package:
  stage: build
  tags:
    - kvm
    - nix
  script: nix-build -A hsnrm --no-build-output

make:doc:
  stage: build
  tags:
    - kvm
    - nix
  script: nix-shell -p gnumake --run "make doc"
