name: builds
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  binaries:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: |
          docker --version
          docker run -d docker://alpine/edge
