name: builds
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  nix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixos-21.04
      - run: nix-build -A nrm-core
  generic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install the right ghc
        run: |
          ghcup install ghc 8.6.5
          ghcup set ghc 8.6.5
      - name: setup dependencies
        run: |
          sudo apt-get install pkg-config libzmq3-dev
      - name: cabal build
        run: | 
          cabal v2-update
          cabal v2-build all
