name: builds
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  binaries:
    runs-on: ubuntu-latest
    container: alpine:edge
    steps:
      - uses: actions/checkout@v2
      - name: setup
        run: |
          apk update
          apk add ghc cabal
          apk add wget pkgconf zeromq
      - name: cabal build
        run: |
          cabal update
          cabal v2-build --disable-shared --enable-static nrm-core-module
