name: builds
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  binaries:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: cache static ghc
        uses: actions/cache@v2
        id: ghc-static
        env:
          cache-name: cache-ghc-static
        with:
          path: ~/.ghcup/ghc/8.6.5
          key: ${{ runner.os }}-build-${{ env.cache-name }}
      - name: compile ghc for static link
        if: steps.ghc-static.outputs.cache-hit != 'true'
        run: |
          ghcup install ghc 8.6.5
          ghcup compile ghc -j 4 -v 8.6.5 -b 8.6.5 --set -c `pwd`/resources/bdist/build.mk -p `pwd`/resources/bdist
      - name: setup
        run: |
          sudo apt-get install pkg-config libzmq3-dev
      - name: cache static cabal deps
        uses: actions/cache@v2
        id: cabal-static
        env:
          cache-name: cache-cabal-static
        with:
          path: ~/.cabal
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.cabal') }}
      - name: cabal build
        run: | 
          ls -aRl ~/.ghcup/
          ghcup list
          ghcup set ghc 8.6.5
          cabal v2-update
          cabal v2-build all
